# Generated by Django 3.0.10 on 2020-09-29 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        ('content', '0003_auto_20200929_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='somepage',
            name='contact_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_on_page', to='forms.FormPage'),
        ),
    ]
